export const HOST_TCB_ATTESTATION_SCHEMA: string;
export const HOST_TCB_ATTESTATION_ROOT: string;
export const HOST_TCB_PIN_DROP_IN: string;
export const HOST_TCB_BOOTSTRAP_PLACEHOLDER_SHA256: string;
export const SEALED_SERVICE_PROPERTIES: readonly string[];
export const EMPTY_SEALED_SERVICE_PROPERTIES: readonly string[];
export const FIXED_SEALED_SERVICE_PROPERTIES: Readonly<Record<string, string>>;
export const REQUIRED_SEALED_ENVIRONMENT: readonly string[];
export const REQUIRED_SEALED_UNSET_ENVIRONMENT: readonly string[];
export function captureLoadedServicePolicy(root: string, digest: string, options?: Record<string, unknown>): Record<string, unknown>;
export function createHostTcbAttestation(options: Record<string, any>): Record<string, unknown>;
export function verifyHostTcbAttestation(bytes: Uint8Array, options: Record<string, any>): { record: Record<string, unknown>; attestationSha256: string };
export function runtimeTrustBindingFromHostAttestation(options: Record<string, any>): any;
export function hostTcbPinDropIn(attestationSha256: string): string;
export function hostTcbPinDropInNormalized(): string;
export function writeCanonicalRootRecord(directory: string, name: string, record: unknown, options?: Record<string, any> & { rawText?: boolean }): { path: string; sha256: string };
export function prepareRootDirectory(path: string, options?: { expectedUid?: number; expectedGid?: number }): string;
export function installHostTcbPinDropIn(systemdRoot: string, releaseDigest: string, attestationSha256: string, options?: { expectedUid?: number; expectedGid?: number }): { path: string; sha256: string };
export function replaceHostTcbBootstrapPinDropIn(systemdRoot: string, releaseDigest: string, attestationSha256: string, options?: { expectedUid?: number; expectedGid?: number }): { path: string; sha256: string };
